# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\GIT\Nodes\OptionsWindow_ui.ui'
#
# Created: Fri Aug 14 15:34:26 2015
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_OptionsUI(object):
    def setupUi(self, OptionsUI):
        OptionsUI.setObjectName("OptionsUI")
        OptionsUI.resize(357, 463)
        self.centralwidget = QtGui.QWidget(OptionsUI)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(1, 1, 1, 1)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.NodesTab = QtGui.QWidget()
        self.NodesTab.setObjectName("NodesTab")
        self.gridLayout_2 = QtGui.QGridLayout(self.NodesTab)
        self.gridLayout_2.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(5, 10, 5, 5)
        self.formLayout.setVerticalSpacing(2)
        self.formLayout.setObjectName("formLayout")
        self.baseColorLabel = QtGui.QLabel(self.NodesTab)
        self.baseColorLabel.setObjectName("baseColorLabel")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.baseColorLabel)
        self.baseColorWidget = QtGui.QWidget(self.NodesTab)
        self.baseColorWidget.setObjectName("baseColorWidget")
        self.gridLayout_3 = QtGui.QGridLayout(self.baseColorWidget)
        self.gridLayout_3.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pb_node_base_color = QtGui.QPushButton(self.baseColorWidget)
        self.pb_node_base_color.setObjectName("pb_node_base_color")
        self.gridLayout_3.addWidget(self.pb_node_base_color, 0, 0, 1, 1)
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.baseColorWidget)
        self.nodeSelectedLineColorLabel = QtGui.QLabel(self.NodesTab)
        self.nodeSelectedLineColorLabel.setObjectName("nodeSelectedLineColorLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.nodeSelectedLineColorLabel)
        self.pb_node_selected_pen_color = QtGui.QPushButton(self.NodesTab)
        self.pb_node_selected_pen_color.setObjectName("pb_node_selected_pen_color")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.pb_node_selected_pen_color)
        self.nodeSelectedLineTypeLabel = QtGui.QLabel(self.NodesTab)
        self.nodeSelectedLineTypeLabel.setObjectName("nodeSelectedLineTypeLabel")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.nodeSelectedLineTypeLabel)
        self.cb_node_selected_line_type = QtGui.QComboBox(self.NodesTab)
        self.cb_node_selected_line_type.setObjectName("cb_node_selected_line_type")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.cb_node_selected_line_type)
        self.nodeLabelBackgroundColorLabel = QtGui.QLabel(self.NodesTab)
        self.nodeLabelBackgroundColorLabel.setObjectName("nodeLabelBackgroundColorLabel")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.nodeLabelBackgroundColorLabel)
        self.pb_node_label_bg_color = QtGui.QPushButton(self.NodesTab)
        self.pb_node_label_bg_color.setObjectName("pb_node_label_bg_color")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.pb_node_label_bg_color)
        self.nodeLabelFontLabel = QtGui.QLabel(self.NodesTab)
        self.nodeLabelFontLabel.setObjectName("nodeLabelFontLabel")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.nodeLabelFontLabel)
        self.fb_node_label_font = QtGui.QFontComboBox(self.NodesTab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.fb_node_label_font.setCurrentFont(font)
        self.fb_node_label_font.setObjectName("fb_node_label_font")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.fb_node_label_font)
        self.nodeLabelFontSizeLabel = QtGui.QLabel(self.NodesTab)
        self.nodeLabelFontSizeLabel.setObjectName("nodeLabelFontSizeLabel")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.nodeLabelFontSizeLabel)
        self.sb_node_label_font_size = QtGui.QSpinBox(self.NodesTab)
        self.sb_node_label_font_size.setMinimum(3)
        self.sb_node_label_font_size.setMaximum(40)
        self.sb_node_label_font_size.setSingleStep(1)
        self.sb_node_label_font_size.setProperty("value", 14)
        self.sb_node_label_font_size.setObjectName("sb_node_label_font_size")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.sb_node_label_font_size)
        self.portColorALabel = QtGui.QLabel(self.NodesTab)
        self.portColorALabel.setObjectName("portColorALabel")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.portColorALabel)
        self.portColorAWidget = QtGui.QWidget(self.NodesTab)
        self.portColorAWidget.setObjectName("portColorAWidget")
        self.gridLayout_4 = QtGui.QGridLayout(self.portColorAWidget)
        self.gridLayout_4.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pb_lyt_a_color = QtGui.QPushButton(self.portColorAWidget)
        self.pb_lyt_a_color.setObjectName("pb_lyt_a_color")
        self.gridLayout_4.addWidget(self.pb_lyt_a_color, 0, 0, 1, 1)
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.portColorAWidget)
        self.portColorBLabel = QtGui.QLabel(self.NodesTab)
        self.portColorBLabel.setObjectName("portColorBLabel")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.portColorBLabel)
        self.portColorBWidget = QtGui.QWidget(self.NodesTab)
        self.portColorBWidget.setObjectName("portColorBWidget")
        self.gridLayout_5 = QtGui.QGridLayout(self.portColorBWidget)
        self.gridLayout_5.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pb_lyt_b_color = QtGui.QPushButton(self.portColorBWidget)
        self.pb_lyt_b_color.setObjectName("pb_lyt_b_color")
        self.gridLayout_5.addWidget(self.pb_lyt_b_color, 0, 0, 1, 1)
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.portColorBWidget)
        self.portColorLabel = QtGui.QLabel(self.NodesTab)
        self.portColorLabel.setObjectName("portColorLabel")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.portColorLabel)
        self.portColorWidget = QtGui.QWidget(self.NodesTab)
        self.portColorWidget.setObjectName("portColorWidget")
        self.gridLayout_6 = QtGui.QGridLayout(self.portColorWidget)
        self.gridLayout_6.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pb_port_color = QtGui.QPushButton(self.portColorWidget)
        self.pb_port_color.setObjectName("pb_port_color")
        self.gridLayout_6.addWidget(self.pb_port_color, 0, 0, 1, 1)
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.portColorWidget)
        self.portDirtyColorLabel = QtGui.QLabel(self.NodesTab)
        self.portDirtyColorLabel.setObjectName("portDirtyColorLabel")
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.portDirtyColorLabel)
        self.portDirtyColorWidget = QtGui.QWidget(self.NodesTab)
        self.portDirtyColorWidget.setObjectName("portDirtyColorWidget")
        self.gridLayout_8 = QtGui.QGridLayout(self.portDirtyColorWidget)
        self.gridLayout_8.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.pb_port_dirty_pen_color = QtGui.QPushButton(self.portDirtyColorWidget)
        self.pb_port_dirty_pen_color.setObjectName("pb_port_dirty_pen_color")
        self.gridLayout_8.addWidget(self.pb_port_dirty_pen_color, 0, 0, 1, 1)
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.portDirtyColorWidget)
        self.portDirtyLineTypeLabel = QtGui.QLabel(self.NodesTab)
        self.portDirtyLineTypeLabel.setObjectName("portDirtyLineTypeLabel")
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.portDirtyLineTypeLabel)
        self.cb_port_dirty_pen_type = QtGui.QComboBox(self.NodesTab)
        self.cb_port_dirty_pen_type.setObjectName("cb_port_dirty_pen_type")
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.cb_port_dirty_pen_type)
        self.nodeSelectedLineColorWidget = QtGui.QWidget(self.NodesTab)
        self.nodeSelectedLineColorWidget.setObjectName("nodeSelectedLineColorWidget")
        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.nodeSelectedLineColorWidget)
        self.portLabelColorLabel = QtGui.QLabel(self.NodesTab)
        self.portLabelColorLabel.setObjectName("portLabelColorLabel")
        self.formLayout.setWidget(13, QtGui.QFormLayout.LabelRole, self.portLabelColorLabel)
        self.portLabelColorWidget = QtGui.QWidget(self.NodesTab)
        self.portLabelColorWidget.setObjectName("portLabelColorWidget")
        self.gridLayout_10 = QtGui.QGridLayout(self.portLabelColorWidget)
        self.gridLayout_10.setContentsMargins(1, 1, 1, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.pb_port_label_color = QtGui.QPushButton(self.portLabelColorWidget)
        self.pb_port_label_color.setObjectName("pb_port_label_color")
        self.gridLayout_10.addWidget(self.pb_port_label_color, 0, 0, 1, 1)
        self.formLayout.setWidget(13, QtGui.QFormLayout.FieldRole, self.portLabelColorWidget)
        self.portLabelFontLabel = QtGui.QLabel(self.NodesTab)
        self.portLabelFontLabel.setObjectName("portLabelFontLabel")
        self.formLayout.setWidget(14, QtGui.QFormLayout.LabelRole, self.portLabelFontLabel)
        self.portLabelFontWidget = QtGui.QWidget(self.NodesTab)
        self.portLabelFontWidget.setObjectName("portLabelFontWidget")
        self.gridLayout_9 = QtGui.QGridLayout(self.portLabelFontWidget)
        self.gridLayout_9.setContentsMargins(1, 1, 1, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.fb_port_label_font = QtGui.QFontComboBox(self.portLabelFontWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.fb_port_label_font.setFont(font)
        self.fb_port_label_font.setObjectName("fb_port_label_font")
        self.gridLayout_9.addWidget(self.fb_port_label_font, 0, 0, 1, 1)
        self.formLayout.setWidget(14, QtGui.QFormLayout.FieldRole, self.portLabelFontWidget)
        self.portFontSizeLabel = QtGui.QLabel(self.NodesTab)
        self.portFontSizeLabel.setObjectName("portFontSizeLabel")
        self.formLayout.setWidget(15, QtGui.QFormLayout.LabelRole, self.portFontSizeLabel)
        self.sb_port_font_size = QtGui.QSpinBox(self.NodesTab)
        self.sb_port_font_size.setMinimum(3)
        self.sb_port_font_size.setMaximum(40)
        self.sb_port_font_size.setProperty("value", 10)
        self.sb_port_font_size.setObjectName("sb_port_font_size")
        self.formLayout.setWidget(15, QtGui.QFormLayout.FieldRole, self.sb_port_font_size)
        self.nodeLabelBackgroundColorWidget = QtGui.QWidget(self.NodesTab)
        self.nodeLabelBackgroundColorWidget.setObjectName("nodeLabelBackgroundColorWidget")
        self.gridLayout_11 = QtGui.QGridLayout(self.nodeLabelBackgroundColorWidget)
        self.gridLayout_11.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.formLayout.setWidget(16, QtGui.QFormLayout.FieldRole, self.nodeLabelBackgroundColorWidget)
        self.nodeLabelFontWidget = QtGui.QWidget(self.NodesTab)
        self.nodeLabelFontWidget.setObjectName("nodeLabelFontWidget")
        self.formLayout.setWidget(17, QtGui.QFormLayout.FieldRole, self.nodeLabelFontWidget)
        self.gridLayout_2.addLayout(self.formLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.NodesTab, "")
        self.SceneTab = QtGui.QWidget()
        self.SceneTab.setObjectName("SceneTab")
        self.gridLayout_12 = QtGui.QGridLayout(self.SceneTab)
        self.gridLayout_12.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setContentsMargins(5, 10, 5, 5)
        self.formLayout_2.setVerticalSpacing(2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.bacgroundColorLabel = QtGui.QLabel(self.SceneTab)
        self.bacgroundColorLabel.setObjectName("bacgroundColorLabel")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.bacgroundColorLabel)
        self.bacgroundColorWidget = QtGui.QWidget(self.SceneTab)
        self.bacgroundColorWidget.setObjectName("bacgroundColorWidget")
        self.gridLayout_13 = QtGui.QGridLayout(self.bacgroundColorWidget)
        self.gridLayout_13.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.pb_scene_bg_color = QtGui.QPushButton(self.bacgroundColorWidget)
        self.pb_scene_bg_color.setObjectName("pb_scene_bg_color")
        self.gridLayout_13.addWidget(self.pb_scene_bg_color, 0, 0, 1, 1)
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.bacgroundColorWidget)
        self.gridColorLabel = QtGui.QLabel(self.SceneTab)
        self.gridColorLabel.setObjectName("gridColorLabel")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.gridColorLabel)
        self.gridColorWidget = QtGui.QWidget(self.SceneTab)
        self.gridColorWidget.setObjectName("gridColorWidget")
        self.gridLayout_14 = QtGui.QGridLayout(self.gridColorWidget)
        self.gridLayout_14.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.pb_grid_color = QtGui.QPushButton(self.gridColorWidget)
        self.pb_grid_color.setObjectName("pb_grid_color")
        self.gridLayout_14.addWidget(self.pb_grid_color, 0, 0, 1, 1)
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.gridColorWidget)
        self.gridLinesTypeLabel = QtGui.QLabel(self.SceneTab)
        self.gridLinesTypeLabel.setObjectName("gridLinesTypeLabel")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.gridLinesTypeLabel)
        self.cb_grid_lines_type = QtGui.QComboBox(self.SceneTab)
        self.cb_grid_lines_type.setObjectName("cb_grid_lines_type")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.cb_grid_lines_type)
        self.edgeColorLabel = QtGui.QLabel(self.SceneTab)
        self.edgeColorLabel.setObjectName("edgeColorLabel")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.edgeColorLabel)
        self.edgeColorWidget = QtGui.QWidget(self.SceneTab)
        self.edgeColorWidget.setObjectName("edgeColorWidget")
        self.gridLayout_15 = QtGui.QGridLayout(self.edgeColorWidget)
        self.gridLayout_15.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.pb_edge_color = QtGui.QPushButton(self.edgeColorWidget)
        self.pb_edge_color.setObjectName("pb_edge_color")
        self.gridLayout_15.addWidget(self.pb_edge_color, 0, 0, 1, 1)
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.edgeColorWidget)
        self.edgeLineTypeLabel = QtGui.QLabel(self.SceneTab)
        self.edgeLineTypeLabel.setObjectName("edgeLineTypeLabel")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.edgeLineTypeLabel)
        self.cb_edge_pen_type = QtGui.QComboBox(self.SceneTab)
        self.cb_edge_pen_type.setObjectName("cb_edge_pen_type")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.cb_edge_pen_type)
        self.edgeLineThicknessLabel = QtGui.QLabel(self.SceneTab)
        self.edgeLineThicknessLabel.setObjectName("edgeLineThicknessLabel")
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.edgeLineThicknessLabel)
        self.sb_edge_thickness = QtGui.QDoubleSpinBox(self.SceneTab)
        self.sb_edge_thickness.setMinimum(0.2)
        self.sb_edge_thickness.setMaximum(10.0)
        self.sb_edge_thickness.setProperty("value", 0.5)
        self.sb_edge_thickness.setObjectName("sb_edge_thickness")
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.sb_edge_thickness)
        self.gridLayout_12.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.SceneTab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        OptionsUI.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(OptionsUI)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 357, 18))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        OptionsUI.setMenuBar(self.menuBar)
        self.actionLoad_options = QtGui.QAction(OptionsUI)
        self.actionLoad_options.setObjectName("actionLoad_options")
        self.actionSave = QtGui.QAction(OptionsUI)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtGui.QAction(OptionsUI)
        self.actionSave_as.setObjectName("actionSave_as")
        self.menuFile.addAction(self.actionLoad_options)
        self.menuFile.addAction(self.actionSave)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(OptionsUI)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(OptionsUI)

    def retranslateUi(self, OptionsUI):
        OptionsUI.setWindowTitle(QtGui.QApplication.translate("OptionsUI", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.baseColorLabel.setText(QtGui.QApplication.translate("OptionsUI", "Node base color", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_node_base_color.setText(QtGui.QApplication.translate("OptionsUI", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeSelectedLineColorLabel.setText(QtGui.QApplication.translate("OptionsUI", "Node selected line color", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_node_selected_pen_color.setText(QtGui.QApplication.translate("OptionsUI", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeSelectedLineTypeLabel.setText(QtGui.QApplication.translate("OptionsUI", "Node selected line type", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeLabelBackgroundColorLabel.setText(QtGui.QApplication.translate("OptionsUI", "Node label background color", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_node_label_bg_color.setText(QtGui.QApplication.translate("OptionsUI", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeLabelFontLabel.setText(QtGui.QApplication.translate("OptionsUI", "Node label font", None, QtGui.QApplication.UnicodeUTF8))
        self.fb_node_label_font.setProperty("currentText", QtGui.QApplication.translate("OptionsUI", "Arial", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeLabelFontSizeLabel.setText(QtGui.QApplication.translate("OptionsUI", "Node label font size", None, QtGui.QApplication.UnicodeUTF8))
        self.portColorALabel.setText(QtGui.QApplication.translate("OptionsUI", "Layout color A", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_lyt_a_color.setText(QtGui.QApplication.translate("OptionsUI", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.portColorBLabel.setText(QtGui.QApplication.translate("OptionsUI", "Layout color B", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_lyt_b_color.setText(QtGui.QApplication.translate("OptionsUI", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.portColorLabel.setText(QtGui.QApplication.translate("OptionsUI", "Port color", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_port_color.setText(QtGui.QApplication.translate("OptionsUI", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.portDirtyColorLabel.setText(QtGui.QApplication.translate("OptionsUI", "Port dirty line color", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_port_dirty_pen_color.setText(QtGui.QApplication.translate("OptionsUI", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.portDirtyLineTypeLabel.setText(QtGui.QApplication.translate("OptionsUI", "Port dirty line type", None, QtGui.QApplication.UnicodeUTF8))
        self.portLabelColorLabel.setText(QtGui.QApplication.translate("OptionsUI", "Port label color", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_port_label_color.setText(QtGui.QApplication.translate("OptionsUI", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.portLabelFontLabel.setText(QtGui.QApplication.translate("OptionsUI", "Port label font", None, QtGui.QApplication.UnicodeUTF8))
        self.fb_port_label_font.setProperty("currentText", QtGui.QApplication.translate("OptionsUI", "MS Shell Dlg 2", None, QtGui.QApplication.UnicodeUTF8))
        self.portFontSizeLabel.setText(QtGui.QApplication.translate("OptionsUI", "Port font size", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.NodesTab), QtGui.QApplication.translate("OptionsUI", "Nodes", None, QtGui.QApplication.UnicodeUTF8))
        self.bacgroundColorLabel.setText(QtGui.QApplication.translate("OptionsUI", "Background color", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_scene_bg_color.setText(QtGui.QApplication.translate("OptionsUI", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.gridColorLabel.setText(QtGui.QApplication.translate("OptionsUI", "Grid color", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_grid_color.setText(QtGui.QApplication.translate("OptionsUI", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLinesTypeLabel.setText(QtGui.QApplication.translate("OptionsUI", "Grid lines type", None, QtGui.QApplication.UnicodeUTF8))
        self.edgeColorLabel.setText(QtGui.QApplication.translate("OptionsUI", "Edge color", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_edge_color.setText(QtGui.QApplication.translate("OptionsUI", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.edgeLineTypeLabel.setText(QtGui.QApplication.translate("OptionsUI", "Edge line type", None, QtGui.QApplication.UnicodeUTF8))
        self.edgeLineThicknessLabel.setText(QtGui.QApplication.translate("OptionsUI", "Edge line thickness", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SceneTab), QtGui.QApplication.translate("OptionsUI", "Scene", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("OptionsUI", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_options.setText(QtGui.QApplication.translate("OptionsUI", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("OptionsUI", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_as.setText(QtGui.QApplication.translate("OptionsUI", "Save as", None, QtGui.QApplication.UnicodeUTF8))

