from datetime import datetime
from Qt.QtWidgets import QFileDialog
from Qt.QtWidgets import QMessageBox
import subprocess
import os

from PyFlow.Core.Common import *
from PyFlow.UI.UIInterfaces import IDataExporter
from PyFlow.Core.version import Version


class CPPCompiler(IDataExporter):
    """docstring for CPPCompiler."""

    def __init__(self):
        super(CPPCompiler, self).__init__()

    @staticmethod
    def createImporterMenu():
        return False

    @staticmethod
    def creationDateString():
        return datetime.now().strftime("%I:%M%p on %B %d, %Y")

    @staticmethod
    def version():
        return Version(1, 0, 0)

    @staticmethod
    def toolTip():
        return "Export c++ hello world program and compile it to executable."

    @staticmethod
    def displayName():
        return "c++ console app"

    @staticmethod
    def doExport(pyFlowInstance):
        script = "// This file was auto-generated by PyFlow exporter '{0} v{1}'\n".format(CPPCompiler.displayName(), str(CPPCompiler.version()))
        script += "// Created: {0}\n\n".format(CPPCompiler.creationDateString())
        script += "#include <iostream>\n\n"
        script += "int main()\n"
        script += "{\n"

        rootGraph = pyFlowInstance.graphManager.get().findRootGraph()
        if len(rootGraph.getNodesList()) == 0:
            QMessageBox.warning(pyFlowInstance, "Warning", "Nothing to export!")
            return

        consoleOutNode = pyFlowInstance.graphManager.get().findNode("consoleOutput")
        if consoleOutNode is None:
            QMessageBox.warning(pyFlowInstance, "Warning", "Console out node not found")
            return

        consoleOutNode[DEFAULT_IN_EXEC_NAME].call()

        script += '\tstd::cout << "{}\\n";\n'.format(consoleOutNode["entity"].getData())

        script += "}\n"

        outFilePath, filterString = QFileDialog.getSaveFileName(filter="c++ source (*.cpp)")
        if outFilePath != "":
            with open(outFilePath, 'w') as f:
                f.write(script)
            cmd = ["g++.exe", outFilePath, "-std=c++11", "-o", outFilePath.replace(".cpp", ".exe")]
            myEnv = os.environ.copy()
            proc = subprocess.Popen(cmd, shell=True, env=myEnv, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
            proc.communicate()
            print("EXE OUTPUT:", subprocess.check_output(outFilePath.replace(".cpp", ".exe")))
