# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:/GIT/nodes/PyFlow/CodeEditor_ui.ui'
#
# Created: Fri Dec 29 17:01:34 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_CodeEditorWidget(object):
    def setupUi(self, CodeEditorWidget):
        CodeEditorWidget.setObjectName("CodeEditorWidget")
        CodeEditorWidget.resize(889, 512)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/resources/py.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CodeEditorWidget.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(CodeEditorWidget)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.leLabel = QtGui.QLineEdit(CodeEditorWidget)
        self.leLabel.setObjectName("leLabel")
        self.verticalLayout.addWidget(self.leLabel)
        self.tabWidget = QtGui.QTabWidget(CodeEditorWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabPins = QtGui.QWidget()
        self.tabPins.setObjectName("tabPins")
        self.gridLayout_3 = QtGui.QGridLayout(self.tabPins)
        self.gridLayout_3.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pbAddInput = QtGui.QPushButton(self.tabPins)
        self.pbAddInput.setObjectName("pbAddInput")
        self.gridLayout_2.addWidget(self.pbAddInput, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 3, 1, 1)
        self.pbAddOutput = QtGui.QPushButton(self.tabPins)
        self.pbAddOutput.setObjectName("pbAddOutput")
        self.gridLayout_2.addWidget(self.pbAddOutput, 0, 4, 1, 1)
        self.pbKillSelectedItems = QtGui.QPushButton(self.tabPins)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/resources/delete_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbKillSelectedItems.setIcon(icon1)
        self.pbKillSelectedItems.setObjectName("pbKillSelectedItems")
        self.gridLayout_2.addWidget(self.pbKillSelectedItems, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scrollArea = QtGui.QScrollArea(self.tabPins)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 436, 392))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_5 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_5.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lwInputs = QtGui.QListWidget(self.scrollAreaWidgetContents)
        self.lwInputs.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.lwInputs.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.lwInputs.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.lwInputs.setUniformItemSizes(False)
        self.lwInputs.setSelectionRectVisible(True)
        self.lwInputs.setObjectName("lwInputs")
        self.gridLayout_5.addWidget(self.lwInputs, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.addWidget(self.scrollArea)
        self.scrollArea_2 = QtGui.QScrollArea(self.tabPins)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 435, 392))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_4 = QtGui.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_4.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lwOutputs = QtGui.QListWidget(self.scrollAreaWidgetContents_2)
        self.lwOutputs.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.lwOutputs.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.lwOutputs.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.lwOutputs.setSelectionRectVisible(True)
        self.lwOutputs.setObjectName("lwOutputs")
        self.gridLayout_4.addWidget(self.lwOutputs, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_3.addWidget(self.scrollArea_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabPins, "")
        self.tabCode = QtGui.QWidget()
        self.tabCode.setObjectName("tabCode")
        self.gridLayout = QtGui.QGridLayout(self.tabCode)
        self.gridLayout.setContentsMargins(1, 1, 1, 1)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget.addTab(self.tabCode, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pbReset = QtGui.QPushButton(CodeEditorWidget)
        self.pbReset.setObjectName("pbReset")
        self.horizontalLayout_4.addWidget(self.pbReset)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.pbSave = QtGui.QPushButton(CodeEditorWidget)
        self.pbSave.setMaximumSize(QtCore.QSize(45, 16777215))
        self.pbSave.setObjectName("pbSave")
        self.horizontalLayout_4.addWidget(self.pbSave)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sbFontSize = QtGui.QSpinBox(CodeEditorWidget)
        self.sbFontSize.setProperty("value", 10)
        self.sbFontSize.setObjectName("sbFontSize")
        self.horizontalLayout_2.addWidget(self.sbFontSize)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(CodeEditorWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CodeEditorWidget)

    def retranslateUi(self, CodeEditorWidget):
        CodeEditorWidget.setWindowTitle(QtGui.QApplication.translate("CodeEditorWidget", "Python node editor", None, QtGui.QApplication.UnicodeUTF8))
        self.leLabel.setText(QtGui.QApplication.translate("CodeEditorWidget", "PythonNode", None, QtGui.QApplication.UnicodeUTF8))
        self.leLabel.setPlaceholderText(QtGui.QApplication.translate("CodeEditorWidget", "Node label...", None, QtGui.QApplication.UnicodeUTF8))
        self.pbAddInput.setText(QtGui.QApplication.translate("CodeEditorWidget", "add input", None, QtGui.QApplication.UnicodeUTF8))
        self.pbAddOutput.setText(QtGui.QApplication.translate("CodeEditorWidget", "add output", None, QtGui.QApplication.UnicodeUTF8))
        self.pbKillSelectedItems.setText(QtGui.QApplication.translate("CodeEditorWidget", "kill selected pins", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPins), QtGui.QApplication.translate("CodeEditorWidget", "Pins", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCode), QtGui.QApplication.translate("CodeEditorWidget", "Code", None, QtGui.QApplication.UnicodeUTF8))
        self.pbReset.setText(QtGui.QApplication.translate("CodeEditorWidget", "reset", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSave.setText(QtGui.QApplication.translate("CodeEditorWidget", "save", None, QtGui.QApplication.UnicodeUTF8))

import nodes_res_rc
